// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"zh": &dictionary{index: zhIndex, data: zhData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"at least one auth mechanism required":                                               23,
	"authentication failed":                                                              15,
	"bad qrcode id":                                                                      21,
	"can't kick current session":                                                         3,
	"can't renewall trial plan":                                                          19,
	"captcha failed":                                                                     30,
	"captcha invalid":                                                                    29,
	"new password should not be the same as original":                                    28,
	"no such email":                                                                      6,
	"no such email address registered":                                                   18,
	"not a valid email address":                                                          16,
	"not this user session":                                                              4,
	"param required":                                                                     2,
	"parameter months must be positive":                                                  14,
	"parameter plan & months required":                                                   13,
	"password invalid":                                                                   27,
	"pls reset your password":                                                            24,
	"rate limited":                                                                       25,
	"session maybe expired, user relogin required":                                       35,
	"ssuser login required":                                                              10,
	"ssuser re-login required":                                                           11,
	"ssuser session expired":                                                             12,
	"the email already occupied":                                                         17,
	"the system is not ready for registering new ss user, pls contact the administrator": 5,
	"the system primary payment service is not ready, pls contact the administrator":     20,
	"there already has one super admin user":                                             1,
	"this order hasn't got any payment service response":                                 22,
	"uncomplete token, user relogin required":                                            33,
	"unknown error":                                                                      0,
	"unrecognized token, user relogin required":                                          32,
	"unrecognized verify action":                                                         26,
	"user login required":                                                                31,
	"user not exists, user relogin required":                                             34,
	"verify code expired":                                                                8,
	"verify code mismatched":                                                             9,
	"verify code required":                                                               7,
}

var enIndex = []uint32{ // 37 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000e, 0x00000035, 0x00000044,
	0x0000005f, 0x00000075, 0x000000c8, 0x000000d6,
	0x000000eb, 0x000000ff, 0x00000116, 0x0000012c,
	0x00000145, 0x0000015c, 0x0000017d, 0x0000019f,
	0x000001b5, 0x000001cf, 0x000001ea, 0x0000020b,
	0x00000225, 0x00000274, 0x00000282, 0x000002b5,
	0x000002da, 0x000002f2, 0x000002ff, 0x0000031a,
	0x0000032b, 0x0000035b, 0x0000036b, 0x0000037a,
	// Entry 20 - 3F
	0x0000038e, 0x000003b8, 0x000003e0, 0x00000407,
	0x00000434,
} // Size: 172 bytes

const enData string = "" + // Size: 1076 bytes
	"\x02unknown error\x02there already has one super admin user\x02param req" +
	"uired\x02can't kick current session\x02not this user session\x02the syst" +
	"em is not ready for registering new ss user, pls contact the administrat" +
	"or\x02no such email\x02verify code required\x02verify code expired\x02ve" +
	"rify code mismatched\x02ssuser login required\x02ssuser re-login require" +
	"d\x02ssuser session expired\x02parameter plan & months required\x02param" +
	"eter months must be positive\x02authentication failed\x02not a valid ema" +
	"il address\x02the email already occupied\x02no such email address regist" +
	"ered\x02can't renewall trial plan\x02the system primary payment service " +
	"is not ready, pls contact the administrator\x02bad qrcode id\x02this ord" +
	"er hasn't got any payment service response\x02at least one auth mechanis" +
	"m required\x02pls reset your password\x02rate limited\x02unrecognized ve" +
	"rify action\x02password invalid\x02new password should not be the same a" +
	"s original\x02captcha invalid\x02captcha failed\x02user login required" +
	"\x02unrecognized token, user relogin required\x02uncomplete token, user " +
	"relogin required\x02user not exists, user relogin required\x02session ma" +
	"ybe expired, user relogin required"

var zhIndex = []uint32{ // 37 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000d, 0x00000020, 0x0000002d,
	0x00000046, 0x0000005f, 0x0000009c, 0x000000ac,
	0x000000bf, 0x000000d2, 0x000000e2, 0x000000ef,
	0x000000ff, 0x0000011e, 0x00000137, 0x00000150,
	0x00000166, 0x0000017f, 0x0000018f, 0x0000019f,
	0x000001b8, 0x000001f8, 0x0000020d, 0x00000229,
	0x00000245, 0x0000025b, 0x00000280, 0x00000299,
	0x000002ac, 0x000002ce, 0x000002e4, 0x000002f7,
	// Entry 20 - 3F
	0x0000030a, 0x00000330, 0x00000359, 0x00000385,
	0x000003ab,
} // Size: 172 bytes

const zhData string = "" + // Size: 939 bytes
	"\x02未知错误\x02已创建管理员\x02参数必须\x02无法踢除当前会话\x02非当前管理员会话\x02系统未就绪，无法注册新用户，请联系管" +
	"理员\x02邮箱未注册\x02请输入验证码\x02验证码已过期\x02验证码错误\x02请先登录\x02请重新登录\x02会话过期，请重新登" +
	"录\x02请指定套餐和月数\x02月数必须为正整数\x02账号或密码错误\x02邮箱地址不合规范\x02邮箱已注册\x02邮箱未注册\x02" +
	"试用套餐无法续费\x02支付系统未就绪，暂时无法续费，请联系管理员\x02错误的二维码ID\x02此订单状态尚未更新\x02请提供密码或验证" +
	"码\x02请重置登录密码\x02操作过于频繁，请稍后重试\x02未识别的验证操作\x02密码不合规范\x02新密码不能和旧密码相同\x02验" +
	"证码不合规范\x02验证码未通过\x02请管理员登录\x02Token无效, 请管理员重新登录\x02Token不完整, 请管理员重新登录" +
	"\x02管理员不存在,请管理员重新登录\x02Token过期, 请管理员重新登录"

	// Total table size 2359 bytes (2KiB); checksum: F0E81FA5
